# Generated by Django 6.0.4 on 2026-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deleted_at_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Mặc định', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='blue', max_length=50),
        ),
    ]
