# Generated by Django 4.2.30 on 2026-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
    ]
