# Generated by Django 6.0.4 on 2026-06-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Mặc định', max_length=100),
        ),
    ]
