# Generated by Django 6.0.4 on 2026-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_char',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_color',
            field=models.CharField(default='bg-blue-500', max_length=50),
        ),
    ]
