# Generated by Django 6.0.5 on 2026-05-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_connection_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
