# Generated by Django 6.0.4 on 2026-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_settings_usersettings_category_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
