# Generated by Django 6.0.4 on 2026-04-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersettings_phone_number'),
        ('events', '0008_event_recurrence_rule_calendargroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='category_management',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='event_settings',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='favorite_calendars',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='language_region',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='view_options',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custom_categories',
            field=models.JSONField(blank=True, default=list, help_text="Danh sách tên danh mục tùy chỉnh, VD: ['Mặc định','Công việc']"),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dim_past_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='first_day_of_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='vi', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_type',
            field=models.CharField(default='screen', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='primary_timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=60),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='region',
            field=models.CharField(default='VN', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='secondary_timezone',
            field=models.CharField(default='America/New_York', max_length=60),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_completed_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_secondary_timezone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_week_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_weekends',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='time_format',
            field=models.CharField(default='24h', max_length=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='week_start_day',
            field=models.CharField(default='monday', max_length=10),
        ),
        migrations.CreateModel(
            name='UserFavoriteCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_key', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='events.calendargroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_userfavoritecalendar',
                'unique_together': {('user', 'calendar_key')},
            },
        ),
    ]
