# Generated by Django 6.0.4 on 2026-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
