# Generated by Django 6.0.4 on 2026-06-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersettings_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='preferences',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custom_categories',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách danh mục tuỳ chỉnh của người dùng, ví dụ: ["TTCS", "CNPM"]'),
        ),
    ]
