# Generated by Django 4.2.30 on 2026-04-18 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('password_reset', 'Quên mật khẩu'), ('bug_report', 'Báo lỗi hệ thống'), ('feedback', 'Góp ý / Phản hồi'), ('feature_request', 'Yêu cầu tính năng'), ('other', 'Khác')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú của admin khi xử lý yêu cầu', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu hỗ trợ',
                'verbose_name_plural': 'Yêu cầu hỗ trợ',
                'ordering': ['-created_at'],
            },
        ),
    ]
