# Generated by Django 6.0.4 on 2026-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_supportrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('bug_report', 'Báo lỗi hệ thống'), ('feedback', 'Góp ý / Phản hồi'), ('feature_request', 'Yêu cầu tính năng'), ('other', 'Khác')], default='other', max_length=20),
        ),
    ]
