# Generated by Django 6.0.4 on 2026-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_deleted_at_event_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Mặc định', max_length=100),
        ),
    ]
