# Generated by Django 6.0.4 on 2026-04-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
