# Generated by Django 4.2.30 on 2026-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_notification_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='connection',
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('invite', 'Event Invitation'), ('accepted', 'Invitation Accepted'), ('declined', 'Invitation Declined'), ('canceled', 'Event Canceled'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('security', 'Security Alert'), ('system', 'System Announcement')], default='invite', max_length=20),
        ),
    ]
