# Generated by Django 6.0.5 on 2026-05-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_notification_reminder_and_email_sent'),
        ('events', '0011_alter_calendargroup_id_alter_calendarshare_id_and_more'),
    ]

    operations = [
    ]
