# Generated by Django 6.0.5 on 2026-05-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_reminder_preference'),
        ('events', '0012_merge_20260521_2305'),
    ]

    operations = [
    ]
