# Generated by Django 6.0.5 on 2026-06-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_merge_20260521_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='Mặc định', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('invite', 'Event Invitation'), ('accepted', 'Invitation Accepted'), ('declined', 'Invitation Declined'), ('canceled', 'Event Canceled'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('security', 'Security Alert'), ('system', 'System Announcement'), ('reminder', 'Event Reminder')], default='invite', max_length=20),
        ),
    ]
