# Generated by Django 6.0.4 on 2026-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_category_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('invite', 'Event Invitation'), ('accepted', 'Invitation Accepted'), ('declined', 'Invitation Declined'), ('canceled', 'Event Canceled'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('friend_declined', 'Friend Request Declined'), ('security', 'Security Alert'), ('system', 'System Announcement'), ('reminder', 'Event Reminder')], default='invite', max_length=20),
        ),
    ]
