# Generated by Django 6.0.4 on 2026-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_attachment_alter_notification_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('invite', 'Event Invitation'), ('accepted', 'Invitation Accepted'), ('declined', 'Invitation Declined'), ('canceled', 'Event Canceled'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('friend_declined', 'Friend Request Declined'), ('security', 'Security Alert'), ('system', 'System Announcement'), ('reminder', 'Event Reminder'), ('task_reminder', 'Task Reminder')], default='invite', max_length=20),
        ),
    ]
