# Generated by Django 6.0.4 on 2026-06-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_notification_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder_minutes',
            field=models.IntegerField(default=10, help_text='Minutes before event to send reminder'),
        ),
    ]
